swagger: "2.0"
info:
  description: 'This is the API for GitPods - git in the cloud.'
  title: GitPods OpenAPI
  version: 1.0.0
  license:
    name: Apache-2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

consumes:
  - application/json
produces:
  - application/json

schemes:
  - http
  - https

basePath: '/v1'

paths:
  /repositories:
    post:
      summary: Create a new repository
      operationId: createRepository
      tags:
        - repositories
      parameters:
        - in: body
          name: newRepository
          required: true
          description: The repository to create
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
              description:
                type: string
              website:
                type: string
      responses:
        200:
          description: The repository has been created and is returned to you
          schema:
            $ref: '#/definitions/repository'
        422:
          description: The new repository has not been created due to invalid input
          schema:
            $ref: '#/definitions/validationError'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
  /repositories/{owner}:
    get:
      summary: Get a owner's repositories
      operationId: getOwnerRepositories
      tags:
        - repositories
      parameters:
        - in: path
          name: owner
          type: string
          required: true
          description: The owner's username
      responses:
        200:
          description: The repositories found by its owner name
          schema:
            type: array
            items:
              $ref: '#/definitions/repository'
        404:
          description: The owner could not be found by this username
          schema:
            $ref: '#/definitions/error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
  /repositories/{owner}/{name}:
    get:
      summary: Get a repository by owner name and its name
      operationId: getRepository
      tags:
        - repositories
      parameters:
        - in: path
          name: owner
          type: string
          required: true
          description: The owner's username
        - in: path
          name: name
          type: string
          required: true
          description: The repository's name
      responses:
        200:
          description: The repository found by its owner and name
          schema:
            $ref: '#/definitions/repository'
        404:
          description: The owner and name combination could not be found
          schema:
            $ref: '#/definitions/error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
  /users:
    get:
      summary: List all users
      operationId: listUsers
      tags:
        - users
      responses:
        200:
          description: An array of all users
          schema:
            type: array
            items:
              $ref: '#/definitions/user'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
  /users/me:
    get:
      summary: Get the current authenticated user
      operationId: getUserMe
      tags:
        - users
      responses:
        200:
          description: The current authenticated user
          schema:
            $ref: '#/definitions/user'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
  /users/{username}:
    get:
      summary: Get a user by their username
      operationId: getUser
      tags:
        - users
      parameters:
        - in: path
          name: username
          type: string
          required: true
          description: The username of a user
      responses:
        200:
          description: The user by their username
          schema:
            $ref: '#/definitions/user'
        404:
          description: The user is not found by their username
          schema:
            $ref: '#/definitions/error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
    patch:
      summary: Update the user's information
      operationId: updateUser
      tags:
        - users
      parameters:
        - in: path
          name: username
          type: string
          required: true
          description: The username of the user to update
        - in: body
          name: updatedUser
          required: true
          description: The updated user
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
      responses:
        200:
          description: The user has been updated
          schema:
            $ref: '#/definitions/user'
        404:
          description: The user could not be found by this username
          schema:
            $ref: '#/definitions/error'
        422:
          description: The updated user has invalid input
          schema:
            $ref: '#/definitions/validationError'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
definitions:
  repository:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
        format: uuid
        readOnly: true
      name:
        type: string
      description:
        type: string
      website:
        type: string
      default_branch:
        type: string
      created_at:
        type: string
        format: 'date-time'
      updated_at:
        type: string
        format: 'date-time'
      owner:
        type: object
        $ref: '#/definitions/user'
  user:
    type: object
    required:
      - id
      - username
    properties:
      id:
        type: string
        format: uuid
        readOnly: true
      email:
        type: string
        format: email
      username:
        type: string
      name:
        type: string
      created_at:
        type: string
        format: 'date-time'
      updated_at:
        type: string
        format: 'date-time'
  validationError:
    type: object
    required:
      - message
    properties:
      message:
        type: string
      errors:
        type: array
        items:
          type: object
          properties:
            field:
              type: string
            message:
              type: string
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
