apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: gitpods-try
spec:
  replicas: 3
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3021"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: api
        image: gitpods/api:latest
        env:
        - name: GITPODS_LISTEN_ADDR
          value: '0.0.0.0:3020'
        - name: GITPODS_DATABASE_DRIVER
          value: 'postgres'
        - name: GITPODS_DATABASE_DSN
          value: 'postgres://postgres:postgres@db:5432?sslmode=disable'
        - name: GITPODS_LOG_JSON
          value: 'true'
        - name: GITPODS_LOG_LEVEL
          value: 'info'
        - name: GITPODS_MIGRATIONS_PATH
          value: /migrations
        - name: GITPODS_SECRET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: secret
        # This hash is not needed and only used to track which version is deployed when using :latest
#        - name: HASH
#          value: {{ build.commit }}
        ports:
        - containerPort: 3020
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3021
            httpHeaders:
              - name: X-Custom-Header
                value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3
