name: sourcepods
description: git in the cloud!
version: 0.0.1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  http: ^0.12.0
  angular_router: ^2.0.0-alpha+21
  angular_forms: ^2.1.1

dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^0.4.4
  test: ^1.5.1
